const SEND_NOTIFICATION = 'SEND_NOTIFICATION';
const RECEIVE_NOTIFICATION = 'RECEIVE_NOTIFICATION';
const REQUEST_NOTIFICATIONS = 'REQUEST_NOTIFICATIONS';
const RECEIVE_NOTIFICATIONS = 'RECEIVE_NOTIFICATIONS';

export default {
    SEND_NOTIFICATION,
    RECEIVE_NOTIFICATION,
    REQUEST_NOTIFICATIONS,
    RECEIVE_NOTIFICATIONS,
}